---

- name: Debian Playbook Update, Upgrade Server, Install NMAP, GIT and Network Tools
  hosts:  debian
  become: True
  become_user: root

  tasks:

  - name: Update Server
    apt:
      update_cache: yes

  - name: Upgrade Server
    apt:
      upgrade: dist

  - name: Install Nmap
    apt:
      pkg: nmap
      state: latest


  - name: Install GIT
    apt:
      pkg: git
      state: latest


  - name: Install Network Tools(ifconfig)
    apt:
      pkg: net-tools
      state: latest

...